#+TITLE: もくもく Emacs #1 を開催しました
#+AUTHOR: momonga
#+DATE: <2015-09-24 Thu 6:11>
#+KEYWORDS: Emacs

東京では、[[http://tokyovim.connpass.com/][TokyoVim]] や [[http://momongavim.connpass.com/][momonga.vim]] などの Vim に関するもくもく会が定期的に開催されています。しかし、Emacs に関してはなかなかもくもく会というものを見かけません。2015年から Emacs を使っている身としては、Emacs でも皆で集まってもくもくしてみたいものです。そこで今回、[[http://mokumokuemacs.connpass.com/event/19416/][もくもくEmacs #1]] というイベントを企画・開催してみました。

会場はピクシブ株式会社さんに提供して頂けることになり、渋谷での開催となりました。ピクシブさん、ありがとうございます。また、日程調整や当日の案内・進行を行ってくださったピクシブ社員さん、ありがとうございました。特に [[https://twitter.com/tadsan][@tadsan]] さん、私が雑に「もくもくEmacs 開催したい」と呟いた際に話に乗って頂きありがとうございます。

*ところでそれとは全く関係のない話で恐縮なのですが、最近私がよく利用しているウェブサービスで [[http://www.pixiv.net/][pixiv]] というものがあるのですが、皆さんご存知でしょうか？*


#+HTML: <span class="sugoi sugoi1" style="color: #0096DB;">pixiv</span>

pixiv は「お絵かきがもっと楽しくなる場所」を目指して作られた、イラストや小説などの投稿・閲覧に特化したソーシャル・ネットワーキング・サービスです。

私はイラストを描くことはしないので、もっぱらアイドルマスターシンデレラガールズなどのイラストを日々閲覧しています。無料でかわいいアイドル達のイラストが見られる大変徳の高いサービスなので、ぜひ皆さんも利用してみてくださいね。

そして、なんと月額540円（税込）の [[http://www.pixiv.net/premium.php][pixivプレミアムサービス]] に入会することで、人気イラストが分かる「人気順検索」や、見たいイラストだけが見れる「サムネイルフィルター」、過去に見たイラストがサムネイルで表示される「閲覧履歴」など、様々便利な機能が使えるようになります。しかも、今ならクレジットカードで登録すると月額540円（税込）が1ヶ月無料になるキャンペーン中です。お得ですね！

よし、では以下、レポートです。

* 集合・もくもく

  13:00 に集合し、若干のアクシデントがあったものの無事もくもく開始しました。会場があるビルの入口前で数人と合流した際、「プログラマは飽くまで副業、本業は [[http://cinderella.idolmaster.jp/][アイドルのプロデューサー]] をやっており、担当アイドルは [[http://dic.pixiv.net/a/%25E8%25BC%25BF%25E6%25B0%25B4%25E5%25B9%25B8%25E5%25AD%2590][輿水幸子]] です」という説明をしたら困惑させてしまった。どうもすみませんでした。

  途中参加・途中退室自由でしたので、その後ちらほらと人があつまり、大体 14:00 頃には皆さん集まった感じだったかと思います。ちなみにイベント説明の趣旨に「Vim script を書いたり」と書いておいたら、Vimmer である [[https://twitter.com/thinca][@thinca]] さんが参戦してくれました。

  ピクシブさんオフィスに揃っている Emacs 関連書籍の豊富さがすごく、話が弾みつつ、各自もくもくしていました。私は主に [[https://twitter.com/tomoyaton][@tomoyaton]] さんに Atom Editor の話を聞いたり、例によって [[https://twitter.com/keno_ss][@keno_ss]] さんに Emacs Lisp について色々質問したり、 =document-at-point= という、カーソル位置の関数や変数のドキュメントをポップアップでその場に表示するためのプラギンを開発したりしてました。本当はもうちょっとカジュアルに席移動して他の人とも話したかった。次はやるぞ！

  あと、ピクシブさんから缶ジュースなどの各種ドリンクが無限に提供されて、タダで飲み放題でした。ありがとうございました。ピクシブさんのオフィスに行けば無限に缶ジュースがタダで手に入ることがわかったので、これからは毎日ピクシブさんのオフィスに寄って大量の缶ジュースを貰い、それを売りさばくことで生計を立てていこうと思いました。よろしくお願いします。

* 成果発表

  19時頃になり、成果発表の時間なので成果発表を行いたい方は成果発表をしましょうということでプロジェクタを利用して成果発表が行われ、成果発表が行われました。記憶が曖昧ですが覚えている発表を書いておきます。抜けてたらごめん。

** [[https://twitter.com/igjit][@igjit]] さん

    - [[https://github.com/igjit/ac-mozc][ac-mozc]] という、auto-complete でバックエンドの Mozc サーバーを叩き日本語入力を行うプラギンがあって、それの改良を行ったとのこと。Emacs と IME との相性を気にしなくてよくなるのはめっちゃ便利そうと思った。
    - ついでに [[https://el-more.herokuapp.com/][el-more]] という、指定パッケージを利用している方が他にどんなパッケージを利用しているかの統計情報を閲覧できるサイトの紹介。GitHub 上で公開されている Caskfile をクロールして DB を構築しているらしい。

** [[https://twitter.com/tadsan][@tadsan]] さん

   [[https://github.com/hayamiz/twittering-mode][twittering-mode]] を fork した twitter クライアント [[https://github.com/zonuexe/twindrill-mode][twindrill-mode]] の紹介。twittering-mode の実装がでかくて中々大変とのこと。Emacs で使えるナウい twitter クライアント期待してます。

** [[https://twitter.com/tomoyaton][@tomoyaton]] さん

    - init.el を 1 から再構築し、約 50 行書く所まで終わったので、その中身をプロジェクタに写しつつ解説。
    - ついでに 21 世紀のエディタ Atom 用に開発した、rubocop を利用した Ruby 用の gofmt 的な自動フォーマッタプラギンの紹介。gofmt 的ツールは今後流行りそうですね。その他 Atom の解説などがあって面白かった。

* 解散、二次会

  お片づけして解散し、その後二次会ということでサイゼリアでごはん食べつつお話をしました。その時の全財産が 1,800 円しかなかったので、サイゼリアは安くて助かった。ちなみにこの記事を書いている今現在の全財産は 134 円です。[[http://www.amazon.co.jp/registry/wishlist/28P9YZ3XLKPRU][ところで私の食料系ほしい物リストはこちらになります]]。

  ごはん食べた後、コード書いたり雑談しながら皆が食べ終わるのを待ち、いい頃合いで切り上げました。


* もくもくEmacs #1 を終えて

  Vim のもくもく会である momonga.vim を開催・運営するにあたって、初心者が気軽に参加しやすいようにイベント説明ページを作るという事を心がけていました。それが功を奏したのか、熟練者/初心者、または常連/新規が良い感じに混ざったバランスの良いもくもく会を運営できているのではないかと思っています。「今日は Vim のインストールをします！」「実は Emacs 使いです」という人が参加するくらいゆるいイベントです。Emacs のもくもく会である もくもくEmacs も、同じくらいゆるい (こわくない = 参加への心理的抵抗の低い) イベントにしていければいいなと思っています。そういう意味では、今回の もくもくEmacs #1 は、良い感じに気が抜けた、和気藹々とした雰囲気のイベントとして上々の滑り出しだったかと思います。今後も定期的に開催していく予定ですので、興味がある方はぜひ参加してみてください。「init.el を書いてみる」どころか「Emacs をインストールする」というところからでもいいんですよ。

  #+HTML: <span class="sugoi sugoi2" style="">welcome</span>

  日本における Emacs のコミュニティは、 Vim のそれと比べてまだまだ活発でないように見えます。もくもくEmacs という、みんなで集まって Emacs について作業をしたり交流を持てる会を定期開催することによって、少しでも日本の Emacs コミュニティ活発化の一因となればいいなと思います。Emacs コミュニティといえば、毎週土曜日に開催されている [[http://emacs-jp.github.io/reading-init.el/about.html][init.el オンライン読書会]] もよろしければどうぞ。
